In [1]:
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
cd Algorithms

/home/olix/Documentos/datos/tp2master/OrgaDatos/TP2/Algorithms

In [2]:
postulations = pd.read_csv('postulantes1M.csv')

In [3]:
postulations.head()

,idpostulante,nombre,estado,nombre_sort,fechanacimiento,sexo,idaviso,fechapostulacion,idpais,titulo,descripcion,nombre_zona,tipo_de_trabajo,nivel_laboral,nombre_area
0,wVYeVqB,Universitario,Graduado,3.0,1960-05-31,MASC,1112266484,2018-01-24 07:37:24,1,EJECUTIVO DE CLIENTES SUCURSAL RIO GALLEGOS,<p>En Banco Macro nos encontramos en la búsque...,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Comercial
1,3Nd3ojJ,Terciario/Técnico,En Curso,2.0,1993-02-26,FEM,1112341140,2018-02-18 19:12:35,1,Vendedor corporativo - CABA,"<p align=""center""><strong>Compañía de Servicio...",Gran Buenos Aires,Full-time,Junior,Ventas
2,0zP38NM,Universitario,En Curso,3.0,1993-12-01,FEM,1112374718,2018-03-19 16:40:55,1,Asesor Comercial La Plata,"<p style=""""><strong><span style="""">Adecco Offi...",Gran Buenos Aires,Full-time,Senior / Semi-Senior,Ventas
3,JBr1VQ5,Secundario,Graduado,1.0,1988-12-17,MASC,1112316544,2018-02-06 16:33:09,1,ADMINISTRATIVO con Lic. de conducir B1 - BARRACAS,<p>Empresa del rubro ascensores incorporará un...,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Logística
4,Rz6RLkO,Secundario,Graduado,1.0,1991-03-19,MASC,1111459399,2018-02-22 17:21:47,1,Operario de Producción,<p><strong>Adecco Industrial </strong>está esp...,Gran Buenos Aires,Full-time,Junior,Producción

In [4]:
postulations.drop(columns=['idpais','fechapostulacion'],inplace = True)

In [5]:
postulations['se_postulo'] = 1

In [6]:
postulations.drop(columns = ['nombre'],inplace = True)

In [7]:
postulations.head()

,idpostulante,estado,nombre_sort,fechanacimiento,sexo,idaviso,titulo,descripcion,nombre_zona,tipo_de_trabajo,nivel_laboral,nombre_area,se_postulo
0,wVYeVqB,Graduado,3.0,1960-05-31,MASC,1112266484,EJECUTIVO DE CLIENTES SUCURSAL RIO GALLEGOS,<p>En Banco Macro nos encontramos en la búsque...,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Comercial,1
1,3Nd3ojJ,En Curso,2.0,1993-02-26,FEM,1112341140,Vendedor corporativo - CABA,"<p align=""center""><strong>Compañía de Servicio...",Gran Buenos Aires,Full-time,Junior,Ventas,1
2,0zP38NM,En Curso,3.0,1993-12-01,FEM,1112374718,Asesor Comercial La Plata,"<p style=""""><strong><span style="""">Adecco Offi...",Gran Buenos Aires,Full-time,Senior / Semi-Senior,Ventas,1
3,JBr1VQ5,Graduado,1.0,1988-12-17,MASC,1112316544,ADMINISTRATIVO con Lic. de conducir B1 - BARRACAS,<p>Empresa del rubro ascensores incorporará un...,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Logística,1
4,Rz6RLkO,Graduado,1.0,1991-03-19,MASC,1111459399,Operario de Producción,<p><strong>Adecco Industrial </strong>está esp...,Gran Buenos Aires,Full-time,Junior,Producción,1

In [8]:
notpostulations = pd.read_csv('no_postulantes1M.csv')

In [9]:
notpostulations.head()

,idaviso,idpostulante,estado,nombre_sort,fechanacimiento,sexo,titulo,descripcion,nombre_zona,tipo_de_trabajo,nivel_laboral,nombre_area,se_postulo
0,1112345596,bOz2q4Y,Graduado,1.0,1982-09-19,MASC,Analista Sr. de Arquitectura de Software JAVA ...,<p><strong>Solutix</strong> se encuentra en bú...,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Programación,0
1,1112345596,3NkQVLP,Abandonado,3.0,1991-08-20,FEM,Analista Sr. de Arquitectura de Software JAVA ...,<p><strong>Solutix</strong> se encuentra en bú...,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Programación,0
2,1112345596,X9PYj5P,En Curso,4.0,1992-02-23,FEM,Analista Sr. de Arquitectura de Software JAVA ...,<p><strong>Solutix</strong> se encuentra en bú...,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Programación,0
3,1112345596,8MPPYv3,En Curso,1.0,1969-05-20,FEM,Analista Sr. de Arquitectura de Software JAVA ...,<p><strong>Solutix</strong> se encuentra en bú...,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Programación,0
4,1112345596,KBaYVqj,NaN,NaN,1976-03-25,MASC,Analista Sr. de Arquitectura de Software JAVA ...,<p><strong>Solutix</strong> se encuentra en bú...,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Programación,0

In [10]:
#Concateno las postulaciones con las NO postulaciones

frames = [postulations,notpostulations]
total = pd.concat(frames, ignore_index = True)

In [11]:
total.drop_duplicates(subset=['idpostulante','idaviso'], keep = 'first',inplace = True)
total.reset_index(inplace = True,drop = True)

In [12]:
total.count()

descripcion        1995275
estado             1950654
fechanacimiento    1958211
idaviso            1995275
idpostulante       1995275
nivel_laboral      1995275
nombre_area        1995275
nombre_sort        1950654
nombre_zona        1995275
se_postulo         1995275
sexo               1995275
tipo_de_trabajo    1995275
titulo             1995275
dtype: int64

In [13]:
total.to_csv("data2M.csv", index = False)