# SVM

In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas.util import hash_pandas_object
from sklearn.ensemble import AdaBoostClassifier

%matplotlib inline

In [8]:
postulations = pd.read_csv('../DataAnalysis/postulaciones_nopostulaciones.csv')

In [12]:
postulations.head()

,Unnamed: 0,idpostulante,idaviso,nombre,estado,fechanacimiento,sexo,idpais,titulo,nombre_zona,tipo_de_trabajo,nivel_laboral,nombre_area,se_postulo
0,0,4rP6q15,1112145679,Doctorado,En Curso,NaN,NO_DECLARA,1,Telecobrador - Importante Banco,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Call Center,1
1,1,RzMvGDo,1112145679,Doctorado,Graduado,1986-08-21,MASC,1,Telecobrador - Importante Banco,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Call Center,1
2,2,owav2La,1112145679,Doctorado,En Curso,1998-03-14,FEM,1,Telecobrador - Importante Banco,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Call Center,1
3,3,1eWdwB,1112145679,Doctorado,Graduado,1981-12-31,FEM,1,Telecobrador - Importante Banco,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Call Center,1
4,4,2zQMWYa,1112145679,Doctorado,Graduado,1989-05-05,FEM,1,Telecobrador - Importante Banco,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Call Center,1

In [9]:
from sklearn.base import TransformerMixin

class DataFrameImputer(TransformerMixin):

    def __init__(self):
        """Impute missing values.

        Columns of dtype object are imputed with the most frequent value 
        in column.

        Columns of other types are imputed with mean of column.

        """
    def fit(self, X, y=None):

        self.fill = pd.Series([X[c].value_counts().index[0]
            if X[c].dtype == np.dtype('O') else X[c].mean() for c in X],
            index=X.columns)

        return self

    def transform(self, X, y=None):
        return X.fillna(self.fill)

In [10]:
data = DataFrameImputer().fit_transform(postulations)

In [11]:
data.head()

,Unnamed: 0,idpostulante,idaviso,nombre,estado,fechanacimiento,sexo,idpais,titulo,nombre_zona,tipo_de_trabajo,nivel_laboral,nombre_area,se_postulo
0,0,4rP6q15,1112145679,Doctorado,En Curso,1993-12-09,NO_DECLARA,1,Telecobrador - Importante Banco,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Call Center,1
1,1,RzMvGDo,1112145679,Doctorado,Graduado,1986-08-21,MASC,1,Telecobrador - Importante Banco,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Call Center,1
2,2,owav2La,1112145679,Doctorado,En Curso,1998-03-14,FEM,1,Telecobrador - Importante Banco,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Call Center,1
3,3,1eWdwB,1112145679,Doctorado,Graduado,1981-12-31,FEM,1,Telecobrador - Importante Banco,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Call Center,1
4,4,2zQMWYa,1112145679,Doctorado,Graduado,1989-05-05,FEM,1,Telecobrador - Importante Banco,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Call Center,1

In [22]:
clf = svm.SVC()
clf.fit(postulations.iloc[:,3:12], postulations.iloc[:,13])

ValueError: could not convert string to float: 'Senior / Semi-Senior'