In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
#Funcion que limpia los datos, quedandose con el nivel de educacion mas alto de casa id de los postulantes.
def education_cleaning(df):
    education_dic= {'Secundario': 1, 'Universitario':3,'Terciario/TÃ©cnico':2, 'Otro':0, 'Posgrado':4, 'Master': 5, 'Doctorado': 6}
    df['nombre_sort'] = df['nombre'].map(education_dic)
    df = df.sort_values(by='nombre_sort', ascending=False)
    df = df.drop_duplicates(subset='idpostulante',keep='first')
    return df

In [4]:
data_postulant_education_test = pd.read_csv('fiuba_1_postulantes_educacion.csv')
data_postulant_education_test =education_cleaning(data_postulant_education_test)
data_postulant_education_test.head()

       idpostulante     nombre    estado  nombre_sort
246142       NrN2dL  Doctorado  Graduado            6
299527      1QkVLxE  Doctorado  Graduado            6
256379       YqM4dq  Doctorado  Graduado            6
345390      ZDrxZdb  Doctorado  En Curso            6
278539       aDY0Z9  Doctorado  Graduado            6

In [5]:
data_postulant_sex_age_test = pd.read_csv('fiuba_2_postulantes_genero_y_edad.csv')
data_postulant_sex_age_test.head()

FileNotFoundError: File b'test/fiuba_2_postulantes_genero_y_edad.csv' does not exist

In [153]:
data_ads_details_test1 = pd.read_csv('test/fiuba_6_avisos_detalle.csv')
data_ads_details_test1.head()

,idaviso,idpais,titulo,descripcion,nombre_zona,ciudad,mapacalle,tipo_de_trabajo,nivel_laboral,nombre_area,denominacion_empresa
0,1573840,1,VENDEDORA/O,Nuestra BÃºsqueda se orienta a la incorporaciÃ³n...,Capital Federal,Flores,NaN,Full-time,Otro,Ventas,RIBEIRO SUC. FLORES
1,1712970,1,INGENIERO DE PRODUCTO,INGENIERO ELECTRICISTA/ELECTRONICO CON CONOCIM...,Capital Federal,NaN,NaN,Full-time,Otro,Otras Ingenierias,Aparatos Electricos Automaticos SA
2,1719970,1,** DiseÃ±adores/as GrÃ¡ficos Quark Express **,DiseÃ±adores/as GrÃ¡ficos Quark Express para Rev...,Capital Federal,NaN,NaN,Full-time,Otro,DiseÃ±o,Revista NEX IT Specialist ? Editorial Poulbert
3,1720060,1,Soporte Tecnico,Estudiante de Sistemas (Lic. en Sistemas de la...,Capital Federal,NaN,NaN,Full-time,Otro,Tecnologia / Sistemas,Tango Software
4,1720280,1,ADSCRIPTO DE GERENCIA,Importante OrganizaciÃ³n AcadÃ©mica Empresarial\...,Buenos Aires (fuera de GBA),NaN,NaN,Full-time,Otro,Otros,Experis

In [154]:
data_ads_details_test2 = pd.read_csv('test/fiuba_6_avisos_detalle_missing_nivel_laboral.csv')
data_ads_details_test2.head()

,idaviso,idpais,titulo,descripcion,nombre_zona,ciudad,mapacalle,tipo_de_trabajo,nivel_laboral,nombre_area,denominacion_empresa,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,1001284385,1,Dejanos tu CV,<p><br />Si est&aacute,s interesado en ser parte del Grupo Las Mar&ia...,as ingres&aacute,y dejanos tus datos.</p>,Corrientes,NaN,NaN,Full-time,NaN,Otros,Establecimiento Las MarÃ­as
1,1110092955,1,para lÃ­nea de producciÃ³n (ref. 28376),<p>Empresas vinculadas a la industria automotr...,GBA Oeste,NaN,NaN,Full-time,NaN,ProducciÃ³n,RANDSTAD,NaN,NaN,NaN
2,1110092958,1,para mantenimiento (ref. 27181),"<p style=""display: inline !important;"">Empresa...",GBA Oeste,NaN,NaN,Full-time,NaN,Mantenimiento,RANDSTAD,NaN,NaN,NaN
3,1110391074,1,TrabajÃ¡ con nosotros,<p><strong>Trabaj&aacute; con nosotros</strong...,Cordoba,NaN,NaN,Full-time,NaN,IngenierÃ­a Industrial,Coca Cola Andina Argentina,NaN,NaN,NaN
4,1110669632,1,TÃ©cnico de Mantenimiento,<p>Experiencia en f&aacute;bricas cosm&eacute;...,GBA Oeste,NaN,", LanÃºs",Full-time,NaN,Mantenimiento,PLUMARI S A,NaN,NaN,NaN

In [155]:
ids_test = pd.read_csv('test/test_final_100k.csv')
ids_test.count()

id              100000
idaviso         100000
idpostulante    100000
dtype: int64

In [156]:
#Uno los datos faltantes con los detalles de los avisos
frames_details = [data_ads_details_test1,data_ads_details_test2]
data_ads_details_test = pd.concat(frames_details, ignore_index = True)
data_ads_details_test.drop_duplicates(inplace = True, keep = 'first')
data_ads_details_test.drop(['Unnamed: 11','Unnamed: 12','Unnamed: 13'],1,inplace=True)
data_ads_details_test.reset_index(drop=True, inplace = True)
data_ads_details_test.head()

,ciudad,denominacion_empresa,descripcion,idaviso,idpais,mapacalle,nivel_laboral,nombre_area,nombre_zona,tipo_de_trabajo,titulo
0,Flores,RIBEIRO SUC. FLORES,Nuestra BÃºsqueda se orienta a la incorporaciÃ³n...,1573840,1,NaN,Otro,Ventas,Capital Federal,Full-time,VENDEDORA/O
1,NaN,Aparatos Electricos Automaticos SA,INGENIERO ELECTRICISTA/ELECTRONICO CON CONOCIM...,1712970,1,NaN,Otro,Otras Ingenierias,Capital Federal,Full-time,INGENIERO DE PRODUCTO
2,NaN,Revista NEX IT Specialist ? Editorial Poulbert,DiseÃ±adores/as GrÃ¡ficos Quark Express para Rev...,1719970,1,NaN,Otro,DiseÃ±o,Capital Federal,Full-time,** DiseÃ±adores/as GrÃ¡ficos Quark Express **
3,NaN,Tango Software,Estudiante de Sistemas (Lic. en Sistemas de la...,1720060,1,NaN,Otro,Tecnologia / Sistemas,Capital Federal,Full-time,Soporte Tecnico
4,NaN,Experis,Importante OrganizaciÃ³n AcadÃ©mica Empresarial\...,1720280,1,NaN,Otro,Otros,Buenos Aires (fuera de GBA),Full-time,ADSCRIPTO DE GERENCIA

In [157]:
merge_postulants_info = pd.read_csv('postulantes.csv')

/home/olix/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (1,2) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [158]:
#Mergeo los data frames sobre la informacion de edad y sexo y educacion del postulante del postulante con 
# Y lo paso a un csv

merge_postulants_info_test = data_postulant_education_test.merge(data_postulant_sex_age_test,on = 'idpostulante', how = 'right')
#merge_postulants_info.to_csv("postulantes.csv", index=False)

In [159]:
merge_postulants_info_test.count()

idpostulante       281385
nombre             253688
estado             253688
nombre_sort        253688
fechanacimiento    268482
sexo               281385
dtype: int64

In [160]:
frames_postulants = [merge_postulants_info,merge_postulants_info_test]
merge_postulants_total = pd.concat(frames_postulants)
merge_postulants_total.drop_duplicates(inplace = True, keep = 'first',subset = 'idpostulante')
merge_postulants_total.count()

idpostulante       504407
nombre             447121
estado             447121
nombre_sort        447121
fechanacimiento    477724
sexo               504407
dtype: int64

In [161]:
merge_postulants_test = ids_test.merge(merge_postulants_total, how = 'left', on = 'idpostulante')
merge_postulants_test.drop_duplicates(inplace = True, keep = 'first')
merge_postulants_test.count()

id                 100000
idaviso            100000
idpostulante       100000
nombre              94265
estado              94265
nombre_sort         94265
fechanacimiento     97042
sexo                99998
dtype: int64

In [166]:
# Mergeo los datos de los postulantes con los avisos y lo paso a un csv
merge_postulants_ads_test = merge_postulants_test.merge(data_ads_details_test,on = 'idaviso',how = 'left')
merge_postulants_ads_test.count()

id                      100000
idaviso                 100000
idpostulante            100000
nombre                   94265
estado                   94265
nombre_sort              94265
fechanacimiento          97042
sexo                     99998
ciudad                     822
denominacion_empresa     99970
descripcion              99988
idpais                   99988
mapacalle                10734
nivel_laboral            95568
nombre_area              99974
nombre_zona              99988
tipo_de_trabajo          99982
titulo                   99988
dtype: int64

In [ ]:
#merge_postulants_ads_test['se_postulo'] es lo que tenemos que predecir

In [167]:
merge_postulants_ads_test.to_csv("100k_info_predecir.csv", index=False)